config/routes.rb
Rails.application.routes.draw do

  

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign-up'}

  root 'favorites#index'
  get '/leagues' => 'leagues#leagues', as: :leagues
  get '/leagues/new' => 'leagues#new', as: :leagues_new
  post '/leagues' => 'leagues#create', as: :leagues_create
  get '/leagues/:id' => 'leagues#show', as: :league
  get 'leagues/favorites' => 'leagues#show'
  get '/leagues/:id/edit' => 'leagues#edit', as: :leagues_edit
  patch '/leagues/:id' => 'leagues#update', as: :leagues_update
  delete '/leagues/:id' => 'leagues#destroy', as: :leagues_destroy

  get '/teams' => 'teams#teams', as: :teams

resources :teams

get '/players' => 'players#players', as: :players
resources :players

namespace :leagues do
  resources :favorites
end
  

resources :favorites
get '/favorites/leagues' => 'favorites#show'
get '/favorites/teams' => 'favorites#show'
get '/favorites/players' => 'favorites#show'

namespace :api do
  namespace :v1 do
    resources :leagues, only: [:index]
    resources :teams, only: [:index]
    resources :players, only: [:index]
  end
end

end

app/models/league.rb
class League < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :league, use: :slugged


  has_many :teams, -> { order 'teams.rank' } 
  
  has_and_belongs_to_many :users

  mount_uploader :photo_url, LogoUploader

end

app/controllers/api/v1/leagues_controller.rb
class Api::V1::LeaguesController < ApplicationController
  def index
    render json: League.all
    
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController

before_action :authenticate_admin!, :only => [:destroy, :edit, :update, :create]

  def leagues
    @leagues = League.all
    

  end

  def new
    @league = League.new
  end
  
  def create
    @league = League.create(params[:league])
    flash[:success] = "League created."
    redirect_to "/leagues/#{@league.slug}"
  end

  def show
    @league = League.friendly.find(params[:id])
    @ranks = Unirest.get("http://football-api.com/api/?Action=standings&APIKey=#{ENV['FOOTBALL_API']}&comp_id=#{@league.football_api_comp_id}",
                    headers: {"Accept" => "application/json"}).body["teams"]
    if @league.sbnation_url != nil
    @sbnation = SimpleRSS.parse open("http://www.sbnation.com/rss/section/#{@league.sbnation_url}/index.xml")
    end
    @goal_com = SimpleRSS.parse open("http://www.goal.com/en-us/feeds/news?id=#{@league.goal_url_id}&fmt=rss&ICID=SP")
    @espn = Unirest.get("http://api.espn.com/v1/sports/soccer/#{@league.espn_shortname}/news/headlines?apikey=#{ENV['ESPN_KEY']}",
                    headers: {"Accept" => "application/json"}).body["headlines"]
  end

  def edit
    @league = League.friendly.find(params[:id])
  end

  def update
    @league = League.friendly.find(params[:id])
    @league.update(params[:league])
    flash[:success] = "League updated."
    redirect_to "/leagues/#{@league.id}"
  end

  def showTeam
    @team = Team.friendly.find(params[:id])
    
  end



  def destroy
    
    @league = League.friendly.find(params[:id])
    @league.destroy
    flash[:alert] = "League deleted."
    redirect_to "/leagues/"
  end

  def user_params
    return params.require(:user).permit(:email, :first_name, :last_name)
  end


end

app/helpers/leagues_helper.rb
module LeaguesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/leagues/edit.html.erb
<div class="row">
  <h1>Edit your league below:</h1>

  <%= render "renders/league_form" %>
</div>

app/views/leagues/leagues.html.erb
<div class="row">
  
    <div class="large-10 medium-10 small-10 medium-offset-1 small-offset-1 large-offset-1 columns">
      <% @leagues[0..3].each do |league| %>
        <div class="large-5 medium-5 small-12 columns fav-leagues">
          <a href="<%= league_path(league.slug) %>"><h2><img src="<%= league.photo_url %>" width="200" height="200" alt=""></h2></a>

        </div>
      <% end %>
        <div class="large-12 medium-5 small-12 columns"></div>
    </div>
</div>

app/views/leagues/new.html.erb
<div class="row">
  <h1>Please enter a new league:</h1>

  <%= render "renders/league_form" %>
</div>

app/views/leagues/show.html.erb
<div class="row" ng-app="app">
  <div class="large-7 columns">
      <% if user_signed_in? %>
    <div ng-controller="favoriteCtrl" ng-init="init(<%= @league.id %>, <%= current_user.leagues.collect(&:id).include?(@league.id) %>)">
        <div class="left" ng-click="favoriteLeague(<%= @league.id %>)">
          <div class="outline" ng-class="{filled: filled}"></div>
        </div>
    </div> 
      <% end %>
    <h4 class="left"><%= @league.league %></h4>
  </div>
  <img src="" alt="">
  <div class="large-7 medium-12 small-12 columns">
    <table class="league-table" ng-controller="rankCtrl" ng-init="init(<%= @league.id %>)">
      <tr>
        <th colspan="2" width="300"><a ng-click="predicate = 'name'; reverse=!reverse">Team</a></th>
        <th width="100"><a href="" ng-click="predicate = 'stand_position'; reverse=!reverse">Rank</a></th>
        <th width="100"><a>Played</a></th>
        <th width="100"><a href="" ng-click="predicate = 'stand_points'; reverse=!reverse">Points</a></th>
      </tr>  
      <tr ng-cloak class="ng-cloak" ng-repeat="team in teams | orderBy: 'name' | orderBy:predicate:reverse | filter:query">
        <td><img src="{{ team.image.photo_url.url }}" width="30" height="30" alt=""></td>
        <td><a href="/teams/{{team.slug}}">{{ team.name }}</a></td>
        <td>{{ team.stand_position }}</td>
        <td>{{ team.rank.stand_overall_gp }}</td>
        <td> {{ team.stand_points }} </td>
      </tr>  
    </table> 
  </div>
  <div class="large-5 medium-12 hide-for-small-only columns">
    <a class="twitter-timeline" href="https://twitter.com/<%= @league.twitter_handle %>" data-widget-id="499305398621315072" data-theme="light" data-link-color="#ff1212" data-chrome="transparent" height="800" data-screen-name="<%= @league.twitter_handle %>">Tweets by @<%= @league.twitter_handle %></a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>
</div>

<div class="row">
  <% counter = 1 %>
  <% @sbnation.entries[1..6].each do |entry| %>
    <% if entry[:content].match(/src="(\S*)"/) != nil && counter < 4%>
      <div class="large-4 medium-4 small-12 columns article-headers">
        <p><a href="<%= entry[:id] %>" target="_blank"><%= entry[:title].force_encoding('UTF-8') %></a></p>
      </div>
      <% counter += 1 %>
    <% end %>
  <% end %>
  <% counter = 1 %>
  <% @sbnation.entries[1..6].each do |entry| %>
    <% if entry[:content].match(/src="(\S*)"/) != nil && counter < 4%>
      <div class="large-4 medium-4 small-12 columns article-headers-image">
        <img src="<%= entry[:content].match(/src="(\S*)"/)[1] %>" alt="">
      </div>
      <% counter += 1 %>
    <% end %>
  <% end %>
  <div class="large-12 columns"></div>
  <% @goal_com.items[0..3].each do |item| %>
    <% if item.description.match(/&quot;&gt;(\D*)&lt/) != nil %>
      <div class="large-5 columns image-margin">
        <img src="<%= item.enclosure_url %>" height="277px" alt="">
      </div>
      <div class="large-3 columns league-sb-article-margin">
        <h5><a href="<%= item.link %>" target="_blank"><%= item.title.force_encoding('UTF-8') %></a></h5> 
        <p><%= item.description.match(/&quot;&gt;(\D*)&lt/)[1] %></p>
      </div>
    <% end %>
  <% end %>
  <% @espn[0..8].each do |headline| %>
    <% if headline["video"].any? %>
      <div class="large-5 columns image-margin">
        <video controls src="<%= headline["video"][0]["links"]["source"]["mezzanine"]["href"]  %>" width="422px" height="234px" poster="<%= headline["video"][0]["posterImages"]["default"]["href"] %>">
        </video>
      </div>
      <div class="large-3 columns article-margin">
        <h5><a href="<%= headline["video"][0]["links"]["web"]["href"] %>" target="_blank"><%= headline["video"][0]["headline"] %></a></h5>
        <p><%= headline["video"][0]["description"] %></p>
      </div>
    <div class="large-8 columns"></div>
    <% elsif headline["images"].any? %>
      <div class="large-5 columns image-margin">
        <img src="<%= headline["images"][0]["url"] %>" height="234" width="417" alt="">
      </div>
      <div class="large-3 columns article-margin">
        <h5><a href="<%= headline["links"]["web"]["href"] %>" target=_"blank"><%= headline["headline"] %></a></h5>
        <p>By <%= headline["byline"] %></p>
        <p><%= headline["linkText"] %></p>
      </div>
    <% end %>
  <% end %>
  <div class="large-12 columns"></div>
</div>

<div class="row">
  
    <% if user_signed_in? && current_user.admin? %>
        <a class="button small red-text-buttons" href="<%= leagues_edit_path(@league.slug) %>">Edit</a>
        <a class="destroy button small red-text-buttons" data-confirm="Are you sure?" data-method="delete" href="<%= "/leagues"%>" rel="nofollow">Destroy</a>
    <% end %>
</div>