config/routes.rb
Rails.application.routes.draw do

  

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign-up'}

  root 'favorites#index'
  get '/leagues' => 'leagues#leagues', as: :leagues
  get '/leagues/new' => 'leagues#new', as: :leagues_new
  post '/leagues' => 'leagues#create', as: :leagues_create
  get '/leagues/:id' => 'leagues#show', as: :league
  get 'leagues/favorites' => 'leagues#show'
  get '/leagues/:id/edit' => 'leagues#edit', as: :leagues_edit
  patch '/leagues/:id' => 'leagues#update', as: :leagues_update
  delete '/leagues/:id' => 'leagues#destroy', as: :leagues_destroy

  get '/teams' => 'teams#teams', as: :teams

resources :teams

get '/players' => 'players#players', as: :players
resources :players

namespace :leagues do
  resources :favorites
end
  

resources :favorites
get '/favorites/leagues' => 'favorites#show'
get '/favorites/teams' => 'favorites#show'
get '/favorites/players' => 'favorites#show'

namespace :api do
  namespace :v1 do
    resources :leagues, only: [:index]
    resources :teams, only: [:index]
    resources :players, only: [:index]
  end
end

end

app/models/favorite.rb
class Favorite

 attr_accessor :type, :user, :id


  def initialize(type, user, id)
    @type =  type
    @user = user
    @id = id
  end


  def add_favorite!
    if @type == "League"
    league = League.find_by(:id => @id)
    @user.leagues << league
    
    elsif @type == "Team"
    team = Team.find_by(:id => @id)
    @user.teams << team
    
    end
  end

  def delete_favorite!
     if @type == "League"
      league = League.find_by(id: params[:id])
      @user.leagues.delete(league)

    elsif @type == "Team"
      team = Team.find_by(:id => @id)
      league = League.find_by(id: params[:id])

    end


  
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  
  def index
    if user_signed_in?
      @favorites = current_user
      @fav_leagues = current_user.leagues
      @fav_teams = current_user.teams
      @fav_players = current_user.players
      if current_user.leagues.any? && current_user.teams.any?
        redirect_to '/favorites/leagues'
      end
    end
  end

  def show
     if user_signed_in?
      @allleagues = League.all
      @allteams = Team.all
      @favorites = current_user
      @fav_leagues = current_user.leagues
      @leagues = {}
      @teams = {}
      @fav_leagues.each do |league, team|
        @leagues[league] = Unirest.get("http://football-api.com/api/?Action=standings&APIKey=#{ENV['FOOTBALL_API']}&comp_id=#{league.football_api_comp_id}",
                    headers: {"Accept" => "application/json"}).body["teams"]
      end
      @fav_teams = current_user.teams

    end
      
  end
  
  def create
    favorite = Favorite.new(params[:type], current_user, params[:id])
    favorite.add_favorite!
    render json: {message: "OK"}, status: 201
  end

  def edit
    
  end

  def update
    
  end

  

  def destroy
    puts params[:type]
    if params[:type] == "League"
    league = League.find_by(id: params[:id])
    current_user.leagues.delete(league)
    render json: {message: "OK"}, status: 201
    elsif params[:type] == "Team"
      team = Team.find_by(id: params[:id])
      current_user.teams.delete(team)
      render json: {message: "OK"}, status: 201
    end
  end

  def user_params
    return params.require(:user).permit(:email, :first_name, :last_name)
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<% if user_signed_in? == false %>
<body class="home-page">



  <div class="row form-margin">

    <div class="large-4 columns home-form">
      <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
      <%= f.error_notification %>
        <div class="form-inputs">
          <%= f.input :email, required: true, autofocus: true, label: false, placeholder: 'your email', :class => 'form-inputs' %>
          <%= f.input :first_name, required: true, autofocus: true, label: false, placeholder: 'first name', :class => 'form-inputs' %>
          <%= f.input :last_name, required: true, autofocus: true, label: false, placeholder: 'last name' %>
          <%= f.input :password, required: true, placeholder: 'password', label: false %>
          <%= f.input :password_confirmation, required: true, placeholder:'confirm password', label: false %>
          <label class="checkbox"><%= f.input_field :remember_me, as: :boolean, inline_label: '   Remember me'  %> </label>
        </div>
        <div class="form-actions action-button-margin">
        <%= f.button :submit, "Sign up", :class => 'small' %>
      
      
    </div>
    </div>
      <% end %>



<div class="large-5 columns home-page-accordion">
<ul class="small-block-grid-1 medium-block-grid-3">
  <li>
    <dl class="accordion" data-accordion="myAccordionGroup">
      <dd class="accordion-navigation">
        <a href="#panel1c">About</a>
        <div id="panel1c" class="content">
          Pick and choose the leagues and teams you want to follow. Following European football leagues can be tough. This will make it easy. Get everything all the info as it happen, get calendar reminders
        </div>
      </dd>
      <dd class="accordion-navigation">
        <a href="#panel2c">Why these European leagues?</a>
        <div id="panel2c" class="content">
          Honestly, that's where all the drama is. These leagues features the best players in the world. So if you don't have time to follow everyone, these are the ones to try.
        </div>
      </dd>
      <dd class="accordion-navigation">
        <a href="#panel3c">How does it work?</a>
        <div id="panel3c" class="content">
          You can view all the leagues and stats without an account - no problem. But if you want a customized page to help you follow your favorite teams and leagues, then you need to register. From there, just choose who all you want to follow. This is awesome!
        </div>
      </dd>
    </dl>
  </li>
</ul>
</div>

<div class="large-2 columns">
<a href="#" class="button league-dropdown" data-dropdown="drop" data-dropdown="hover1" data-options="is_hover:true">Leagues &raquo;</a>
<ul id="drop" class="medium large content f-dropdown" data-dropdown-content>
  <li><a href="leagues/bundesliga">Bundesliga</a></li>
  <li><a href="/leagues/english-premier-league">English Premier League</a></li>
  <li><a href="/leagues/la-liga">La Liga</a></li>
  <li><a href="/leagues/serie-a">Serie A</a></li>
  
</ul>
</div>


<div class="row">
<div class="large-4 columns home-form login-form hidden-form">    

<%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, required: false, autofocus: true, label: false, placeholder: 'your email' %>
    <%= f.input :password, required: false, label: false, placeholder: 'your password' %>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Login", :class => 'small' %>
  </div>
<% end %>

</div>
</div>
</div>
</body>
<% end %>

<% if user_signed_in? %>
<body>
  <div class="row">
    <div class="columns large-2">
      <ul id="favorites-nav">
        <li><a href="/favorites/leagues">Leagues</a></li>
        <li><a href="/favorites/teams">Teams</a></li>
      </ul>
    </div>
    <div class="columns large-9 large-offset-1">
      <h3>Favorites!</h3>
      <% if current_user.leagues.empty? && current_user.teams.empty?%>
      <h4>It looks like you haven't favorited any leagues or teams yet. Get started here:</h4>
      <h5><a href="<%= leagues_path %>">Leagues</h5>
      <h5><a href="/favorites/teams">Teams</a></h5>
      <% elsif current_user.leagues.empty?%>
      <h5>You've got some teams, let's get you started with some <a href="<%= leagues_path %>">leagues</a></h5>
      <% @fav_teams.each do |team| %>
        <div class="large-4 medium-5 small-12 columns fav-teams">
          <a href="<%= team_path(team.slug) %>"><h2><img src="<%= team.photo_url %>" width="200" height="200" alt=""></h2></a>
        </div>
      <% end %>
        <div class="large-12 columns"></div>

      <% elsif current_user.teams.empty? %>
      <h5>You've got some leagues, let's get you started with some <a href="<%= leagues_path %>">teams</a></h5>
    <% @fav_leagues.each do |league| %>
        <div class="large-4 medium-5 small-12 columns fav-leagues">
          <a href="/favorites/leagues"><h2><img src="<%= league.photo_url %>" width="200" height="200" alt=""></h2></a>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
</body>
<% end %>

app/views/favorites/show.html.erb
<div class="row">
  <div class="columns large-2">
    <ul id="favorites-nav">
      <li><a href="/favorites/leagues">Leagues</a></li>
      <li><a href="/favorites/teams">Teams</a></li>
    </ul>
  </div>
  <% if current_page?('/favorites/leagues') %>

  <% if current_user.leagues.empty? %>
  <div class="large-offset-1 large-8 columns">
  <h3>Looks like you need to get favoriting! Here are the Leagues on the site:</h3>
  <% @allleagues[0..3].each do |league| %>
    <ul class="no-fav-leagues">
      <li><h5><a href="<%= league_path(league.slug) %>"><%= league.league %></a></h5></li>
    </ul>
  <% end %>
</div>
  <% end %>

    <div class="columns large-8 large-offset-1">
      <% @leagues.each do |league, ranks| %>
        <h3 class="subheader"><a href="<%= league_path(league.slug) %>"><%= league.league %></a></h3>
        <table class="league-table">
          <tr>
            <th width="200px"><%= link_to "Team", :sort => 'name' %></th>
            <th>Rank</th>
            <th>Games Played</th>
            <th>League points</th>
          </tr>  
          <% ranks[0..3].each do |team| %>
          <tr>
            <td><%= team["stand_team_name"] %></td>
            <td><%= team["stand_position"] %> </td>
            <td><%= team["stand_overall_gp"] %></td>
            <td><%= team["stand_points"] %></td>
          </tr>
          <% end %>
        </table>
      <% end %>
    </div>
    
</div>
  <!-- <hr id="favorite-page-line"> -->
<div class="row">
  <% elsif current_page?('/favorites/teams') %>

  <% if current_user.teams.empty? %>
  <div class="large-offset-1 columns large-6">
    <h3>Looks like you need to get favoriting! Here's a quick run-down </h3>
  </div>
    <% grouped_teams = @allteams.group_by {|team|team.league} %>
      <% grouped_teams.each do |league, teams| %>
        <div class="large-12 columns all-teams-list">
          <h3><%= league.league %></h3>
            <% teams.each do |team| %>
              <div class="large-4 columns">
                <h5><a href="<%= team_path(team.slug) %>"><%= team.name %></a></h5>
              </div>
            <% end %>
        </div>
      <% end %>
    <% end %>
    <% grouped_teams = @fav_teams.group_by {|team|team.league} %>
      <% counter = 1 %>
    <% grouped_teams.each do |league, teams| %>
      <% teams.each do |team| %>
      <% if counter < 7%>
        <div class="large-4 columns large-offset-1">
          <table class="fav-teams-table">
            <tr>
              <td><img src="<%= team.photo_url %>" width="35px" height="35px" alt=""></td>
              <td width="100px" height="50px"><a href="<%= team_path(team.slug) %>"><%= team.name %></a></td>
            </tr>
          </table>
        </div>
        <% end %> 
      <% end %>
    <% end %>
      <div class="large-12 columns"></div>
</div>

  <% elsif current_page?('/favorites/players') %>
  <!-- this is code for assigning leagues to teams - I dont' want it to show right now -->
  <% end %>