config/routes.rb
Rails.application.routes.draw do

  

devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout', :sign_up => 'sign-up'}

  root 'favorites#index'
  get '/leagues' => 'leagues#leagues', as: :leagues
  get '/leagues/new' => 'leagues#new', as: :leagues_new
  post '/leagues' => 'leagues#create', as: :leagues_create
  get '/leagues/:id' => 'leagues#show', as: :league
  get 'leagues/favorites' => 'leagues#show'
  get '/leagues/:id/edit' => 'leagues#edit', as: :leagues_edit
  patch '/leagues/:id' => 'leagues#update', as: :leagues_update
  delete '/leagues/:id' => 'leagues#destroy', as: :leagues_destroy

  get '/teams' => 'teams#teams', as: :teams

resources :teams

get '/players' => 'players#players', as: :players
resources :players

namespace :leagues do
  resources :favorites
end
  

resources :favorites
get '/favorites/leagues' => 'favorites#show'
get '/favorites/teams' => 'favorites#show'
get '/favorites/players' => 'favorites#show'

namespace :api do
  namespace :v1 do
    resources :leagues, only: [:index]
    resources :teams, only: [:index]
    resources :players, only: [:index]
  end
end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title><%= content_for?(:title) ? yield(:title) : "Eur Leagues" %></title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "vendor/modernizr" %>
      <%= csrf_meta_tags %>
      <%= favicon_link_tag image_path('favicon.ico') %>
      <link href='http://fonts.googleapis.com/css?family=Dosis' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    </head>

<% flash.each do |name, message| %>
  <div class="alert-box radius <%= name %>">
    <%= message %>
  </div>
<% end %>
  
<body>
  <div class="main-wrapper">
    <!-- Beginning of Top Nav Bar -->
    <div class="contain-to-grid">
      <nav class="top-bar" data-topbar>
        <ul class="title-area">
          <li class="name">
            <h1><a href="/">Eur Leagues</a></h1>
          </li>
          <li class="toggle-topbar"><a href="#"><span></span></a></li>
        </ul>
        
        <section class="top-bar-section">
          <!-- Right Nav Section -->
          <ul class="right">
            <li class="divider"></li>
            <li class="has-dropdown"><a href="<%= leagues_path %>">Leagues</a>
              <ul class="dropdown">
                <li><a href="/leagues/bundesliga">Bundesliga (Germany)</a> </li>
                <li><a href="/leagues/la-liga">La Liga (Spain)</a></li> 
                <li><a href="/leagues/english-premier-league">Premier League (England)</a></li>
                <li><a href="/leagues/serie-a">Serie A (Italy)</a></li>
              </ul>
            </li>
            <li class="divider"></li>
            <li class="has-dropdown">
              <a href="#">Account</a>
              <ul class="dropdown">
                <% if user_signed_in? === false %>
                  <li><a href="/sign-up">Sign up</a></li>
                  <li><a href="/login">Sign in</a></li>
                <% end %>
                <% if user_signed_in? %>
                  <li><a data-method="delete" rel="nofollow" href="/logout">Sign Out</a></li>
                <% end %>
              </ul>
            </li>
            <li class="divider"></li>
          </ul>

          <!-- Left Nav Section -->
          <% if user_signed_in? %>
          <ul class="left">
            <li class="divider"></li>
            <li><a href="/">Your Favorites</a></li>
            <li class="divider"></li>
          </ul>
          <% end %>

        </section>
      </nav>
    <!-- End of Top Nav Bar -->
    
    </div>
    <%= yield %>
  </div>
    <div class="push-footer">
      
    </div>
    
    <footer>
      <div class="row">
      <h3 class="footer-header"><a href="mailto:trevordjones@outlook.com">Contact site owner</a><span class="footer-divider">|</span></h3>
      <h3 class="footer-header"><a href="<%= leagues_path %>">Leagues</a></h3>
      <% if user_signed_in? %>
      <h3 class="footer-header"><span class="footer-divider">|</span><a href="<%= favorites_path %>">Your Favorites</a></h3>
      <% end %>
      <h4 id="copyright">&#169 Trevor Jones <span class="footer-divider">|</span> 2014</h4>
      </div>
      
    </footer>  

<%= javascript_include_tag "application" %>
</body>  
</html>